---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: camp
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHk4bjB6ZTNvCg==
  CLOUDINARY_KEY: MjE0OTE0MjQzNzM5MTI3Cg==
  CLOUDINARY_SECRET: bmFhZUVvWjYtaTg5RFM0RzU1ZkJrM1V6Q1pjCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2ljMmgxWW1oaGJUSXdNalVpTENKaElqb2lZMngzYzNka1p6Z3dNREJzZWpKeGMyRmtiRzFvWW5RNFpTSjkuWmZ3RlU1NXpPV2dULXU0SDhaMTlOUQo=
  DB_URL: bW9uZ29kYitzcnY6Ly9zaHViaGFtc3NjMTAwOkViRmlETGN6SWJTMG5KVmVAcHJvamVjdDAuZ3lzdHc4ci5tb25nb2RiLm5ldC9wcm9qZWN0MAo=
  SECRET: ZGV2b3Bzc2hhY2sK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: camp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: shubhamshinde2025/fullstack:v1
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: camp
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
